apiVersion: str(required=False)
name: str()
description: str(required=False)
type: str(required=False)
kubeVersion: str(required=False)
version: str()
appVersion: any(str(), num(), required=False)
home: str(required=False)
icon: str(required=False)
sources: list(str(), required=False)
maintainers: list(include('maintainer'), required=False)
engine: str(required=False)
keywords: list(str(), required=False)
condition: str(required=False)
tags: str(required=False)
deprecated: bool(required=False)
annotations: map(str(), str(), required=False)
---
maintainer:
  name: str(required=False)
  email: str(required=False)
  url: str(required=False)
