chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - opencontext=https://helm.opencontext.com
chart-dirs:
  - charts
target-branch: main
lint-conf: .github/lintconf.yaml
chart-yaml-schema: .github/chart_schema.yaml
check-version-increment: true
debug: true
exclude-deprecated: true
helm-extra-args: --timeout 600s
validate-maintainers: false
