chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - opencontext=https://helm.opencontext.com
chart-dirs:
  - charts
target-branch: main
check-version-increment: true
debug: true
exclude-deprecated: true
helm-extra-args: --timeout 300s
validate-maintainers: false
