app:
  orgName: Scatter.ly Demo Org
  github:
    authType: token
    token: GH_TOKEN
  catalog:
    locations:
      githubOrg:
        - https://github.com/scatter-ly
      githubDiscovery:
        - https://github.com/scatter-ly/sandbox/
