apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencontext.fullname" . }}-config
  labels:
    {{- include "opencontext.labels" . | nindent 4 }}
data:
  app-config.yaml: |
    {{- if .Values.app.database.connection.ssl.enabled }}
    backend:
      database:
        connection:
          ssl:
            rejectUnauthorized: {{ .Values.app.database.connection.ssl.rejectUnauthorized | default false }}
            ca:
              $file: ../db-ca/ca.crt
            cert:
              $file: ../db-certs/tls.crt
            key:
              $file: ../db-certs/tls.key
    {{- end }}
    integrations:
      # For each github host, choose to auth either via token or github app credentials. Do NOT use both!
      github:
        - host: {{ .Values.app.github.host | default "github.com" }}
          includeArchived: {{ .Values.app.github.includeArchived | default false }}
          {{- if eq .Values.app.github.authType "token" }}
          token:
            $file: ../secrets/GITHUB_TOKEN
          {{- else }}
          apps:
            - $include: ../github/github-app-auth.yaml
          {{- end }}
      {{- if .Values.app.bitbucket.enabled }}
      bitbucket:
        - host: {{ .Values.app.bitbucket.host | default "bitbucket.org" }}
          {{- if eq .Values.app.bitbucket.authType "token" }}
          token:
            $file: ../secrets/BITBUCKET_SECRET
          {{- else }}
          username: {{ .Values.app.bitbucket.appAuth.username }}
          appPassword:
            $file: ../secrets/BITBUCKET_SECRET
          {{- end }}
      {{- end }}
      {{- if .Values.app.googleCloudStorage.enabled }}
      googleGcs:
        # See https://cloud.google.com/docs/authentication/application-default-credentials for credential search order
        # Set environment variable GOOGLE_APPLICATION_CREDENTIALS to the PATH of the service account file
        clientEmail: # Deliberately not set
        privateKey:  # Deliberately not set
      {{- end }}
    auth:
      ### Set this to a valid provider. google or guest
      {{- if not .Values.app.auth.enabled }}
      activeProvider: guest
      {{- else }}
      activeProvider: google
      providers:
        # See https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow for how to get clientId and clientSecret
        google:
          onprem:
            clientId:
              $file: ../secrets/GOOGLE_OAUTH_CLIENT_ID
            clientSecret:
              $file: ../secrets/GOOGLE_OAUTH_CLIENT_SECRET
      {{- end }}
    {{- if .Values.app.clocks }}
    homepage:
      clocks:
        {{- range $k, $v := .Values.app.clocks }}
        - label: {{ $v.label | quote }}
          timezone: {{ $v.timezone | quote }}
        {{- end }}
    {{- end }}
