apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencontext.fullname" . }}
  labels:
    {{- include "opencontext.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7007
      protocol: TCP
      name: http
  selector:
    {{- include "opencontext.selectorLabels" . | nindent 4 }}
