{{- if and (ne .Values.app.github.authType "token") .Values.app.github.appAuth.createAppAuthFromFile }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ required ".Values.app.github.appAuth.appAuthSecret is required" .Values.app.github.appAuth.appAuthSecret }}
  labels:
    {{- include "opencontext.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/resource-policy": "keep"
data:
  github-app-auth.yaml: {{ .Files.Get .Values.app.github.appAuth.createAppAuthFromFile | b64enc }}
{{- else if ne .Values.app.github.authType "token" }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (required ".Values.app.github.appAuth.appAuthSecret is required" .Values.app.github.appAuth.appAuthSecret)).data | default dict }}
{{- if not (hasKey $secretObj "github-app-auth.yaml") }}
{{- fail (printf "\n\nPlease create the '%s' secret with your GitHub app credentials:\n  kubectl create secret generic %s --from-file=github-app-auth.yaml=/$PATH_TO/github-app-auth.yaml --namespace %s \n" .Values.app.github.appAuth.appAuthSecret .Values.app.github.appAuth.appAuthSecret .Release.Namespace) }}
{{- end }}
{{- end }}
