{{- if and .Values.app.googleCloudStorage.enabled .Values.app.googleCloudStorage.useServiceAccount }}
{{- if .Values.app.googleCloudStorage.createServiceAccountFromFile }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ required ".Values.app.googleCloudStorage.serviceAccountSecret" .Values.app.googleCloudStorage.serviceAccountSecret }}
  labels:
    {{- include "opencontext.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/resource-policy": "keep"
data:
  gcp-sa-credentials.json: {{ .Files.Get .Values.app.googleCloudStorage.createServiceAccountFromFile | b64enc }}
{{- else }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (required ".Values.app.googleCloudStorage.serviceAccountSecret is required" .Values.app.googleCloudStorage.serviceAccountSecret)).data | default dict }}
{{- if not (hasKey $secretObj "gcp-sa-credentials.json") }}
{{- fail (printf "\n\nPlease create the '%s' secret with your Google Service Account key:\n  kubectl create secret generic %s --from-file=gcp-sa-credentials.json=/$PATH_TO/gcp-sa-credentials.json --namespace %s \n" .Values.app.googleCloudStorage.serviceAccountSecret .Values.app.googleCloudStorage.serviceAccountSecret .Release.Namespace) }}
{{- end }}
{{- end }}
{{- end }}
