{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required ".Values.postgresql.primary.initdb.scriptsSecret is required" .Values.postgresql.primary.initdb.scriptsSecret }}
  labels:
      {{- include "opencontext.postgresql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  create-backend-dbs.sql: |
    {{ tpl (.Files.Get "files/create-backend-dbs.sql") . | b64enc }}
{{- end }}

