{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ required ".Values.postgresql.tls.certificatesSecret is required" .Values.postgresql.tls.certificatesSecret }}
  labels:
    {{- include "opencontext.postgresql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ include "opencontext.postgresql.generateCerts" . | indent 2 }}
{{- else }}
{{- if not ( lookup "v1" "Secret" .Release.Namespace (required ".Values.postgresql.tls.certificatesSecret is required" .Values.postgresql.tls.certificatesSecret) ) }}
{{- fail (printf "\n\nPlease create the '%s' secret with the SSL certificate and key for your existing postgresql:\n  kubectl create secret tls %s --cert=/$PATH_TO/tls.crt --key=/$PATH_TO/tls.key --namespace %s \n" .Values.postgresql.tls.certificatesSecret .Values.postgresql.tls.certificatesSecret .Release.Namespace) }}
{{- end }}
{{- end }}
