{{ if .Values.ingress.albManageTraffic.prevService.version -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.albManageTraffic.prevService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apple-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "apple-svc.prevSelectorLabels" . | nindent 4 }}
    app.kubernetes.io/version: {{ .Values.ingress.albManageTraffic.prevService.version | quote }}

---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apple-svc.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apple-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "apple-svc.selectorLabels" . | nindent 4 }}
