# Forked: https://github.com/DataDog/helm-charts/blob/main/.github/workflows/ci.yaml
name: Lint and Test Charts

on:
  pull_request:

jobs:
  changed:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.list-changed.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
      - name: Configure Git
        run: |
          git config user.name "OpenContext Bot"
          git config user.email "100982940+opencontext-bot@users.noreply.github.com"
      - name: Check and update opencontext appVersion
        env:
          TOKEN: '${{ secrets.OC_BOT_GH_WRITE_TOKEN }}'
        run: .github/release-opencontext-version.sh
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo -n "Charts changed:"
            echo "$changed"
            echo "::set-output name=changed::$changed"
          else
            echo "PR without any chart changes - failing"
            exit 1
          fi

  lint-chart:
    runs-on: ubuntu-latest
    needs:
      - changed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
      - name: Copy example values into ci/
        run: cp charts/opencontext/examples/*-values.yaml charts/opencontext/ci/
      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs:
      - changed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm Docs
        uses: envoy/install-helm-docs@v1.0.0
        with:
          version: 1.11.0
      - name: Run helm-docs
        run: |
          helm-docs
          git diff --exit-code

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - changed
    strategy:
      matrix:
        # When changing versions here, check that the version exists at: https://github.com/yannh/kubernetes-json-schema and https://hub.docker.com/r/kindest/node/tags
        k8s:
          - v1.26.1   # latest k3s version
          - v1.24.9   # GKE
          - v1.21.2   # Min version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add opencontext helm repo
        run: |
          helm repo add vector https://helm.opencontext.com
          helm repo update
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
          CHANGED_CHARTS: ${{needs.changed.outputs.charts}}
        run: .github/kubeval.sh

  install-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - kubeval-chart
    strategy:
      matrix:
        # When changing versions here, check that the version exists at: https://github.com/yannh/kubernetes-json-schema and https://hub.docker.com/r/kindest/node/tags
        k8s:
          - v1.26.1   # latest k3s version
          - v1.24.9   # GKE
          - v1.21.2   # Min version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create kind ${{ matrix.k8s }}
        uses: helm/kind-action@main
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
      - name: Copy example values into ci/
        run: cp charts/vector/examples/*-values.yaml charts/vector/ci/
      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml --upgrade

  pr-validated:
    name: pr-validated
    runs-on: ubuntu-latest
    needs:
      - install-chart
    steps:
      - name: validate
        run: echo "PR OK"
