# Forked: https://github.com/DataDog/helm-charts/blob/main/.github/workflows/release.yaml
name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "OpenContext Bot"
          git config user.email "100982940+opencontext-bot@users.noreply.github.com"
      - name: Add repo
        run: |
          helm repo add opencontext https://helm.opencontext.com
          helm repo update
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: '${{ secrets.OC_BOT_GH_WRITE_TOKEN }}'
          CR_SKIP_EXISTING: true
