# Forked: https://github.com/DataDog/helm-charts/blob/main/.github/workflows/release.yaml
name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref || github.run_id }}
  cancel-in-progress: true


jobs:
  release:
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: '${{ secrets.OC_BOT_GH_WRITE_TOKEN }}'
      - name: Configure Git
        run: |
          git config user.name "OpenContext Bot"
          git config user.email "100982940+opencontext-bot@users.noreply.github.com"
      - name: Install Helm Docs
        uses: envoy/install-helm-docs@v1.0.0
        with:
          version: 1.11.3
      - name: Run helm-docs to regenerate chart README
        run: helm-docs -t README.md.gotmpl -o README.md
      - name: Add repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add opencontext https://helm.opencontext.com
          helm repo update
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: .github/cr.yaml
        env:
          CR_TOKEN: '${{ secrets.OC_BOT_GH_WRITE_TOKEN }}'
          CR_SKIP_EXISTING: true
